//
//  CrashReportingManager.swift
//  LocalAI
//
//  Created by Tudor.
//

import Foundation
import MetricKit

/// Captures crash, hang, and exception diagnostics via Apple's on-device
/// MetricKit framework and persists them to disk so they survive app restarts.
///
/// This needs no third-party SDK or network endpoint: MetricKit payloads are
/// generated by the system (typically delivered once a day, or on next
/// launch after a crash) and are otherwise only visible in Xcode Organizer,
/// which isn't reachable for a TestFlight tester or a released build. Storing
/// them locally lets diagnostics be exported for support requests via the
/// "Diagnostics" row in Settings.
@Observable
final class CrashReportingManager: NSObject {
    static let shared = CrashReportingManager()

    private let maxStoredReports = 20

    private var diagnosticsDirectory: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let dir = base.appendingPathComponent("Diagnostics", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    private override init() {
        super.init()
    }

    func start() {
        MXMetricManager.shared.add(self)
    }

    /// Saved diagnostic report files, most recent first.
    var savedReports: [URL] {
        let files = (try? FileManager.default.contentsOfDirectory(
            at: diagnosticsDirectory,
            includingPropertiesForKeys: [.contentModificationDateKey]
        )) ?? []
        return files.sorted { lhs, rhs in
            let lhsDate = (try? lhs.resourceValues(forKeys: [.contentModificationDateKey]))?.contentModificationDate ?? .distantPast
            let rhsDate = (try? rhs.resourceValues(forKeys: [.contentModificationDateKey]))?.contentModificationDate ?? .distantPast
            return lhsDate > rhsDate
        }
    }

    func deleteAllReports() {
        for url in savedReports {
            try? FileManager.default.removeItem(at: url)
        }
    }

    private func save(_ data: Data, kind: String) {
        let formatter = ISO8601DateFormatter()
        let name = "\(kind)-\(formatter.string(from: Date())).json"
        let url = diagnosticsDirectory.appendingPathComponent(name)
        try? data.write(to: url, options: .atomic)
        pruneOldReports()
    }

    private func pruneOldReports() {
        let reports = savedReports
        guard reports.count > maxStoredReports else { return }
        for url in reports[maxStoredReports...] {
            try? FileManager.default.removeItem(at: url)
        }
    }
}

extension CrashReportingManager: MXMetricManagerSubscriber {
    func didReceive(_ payloads: [MXMetricPayload]) {
        for payload in payloads {
            save(payload.jsonRepresentation(), kind: "metric")
        }
    }

    func didReceive(_ payloads: [MXDiagnosticPayload]) {
        for payload in payloads {
            guard payload.crashDiagnostics != nil
                || payload.hangDiagnostics != nil
                || payload.cpuExceptionDiagnostics != nil
                || payload.diskWriteExceptionDiagnostics != nil
            else { continue }
            save(payload.jsonRepresentation(), kind: "diagnostic")
        }
    }
}
